# Generated by Django 4.2.23 on 2025-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('TOP', 'Top'), ('BOTTOM', 'Bottom'), ('DRESS', 'Dress'), ('OUTERWEAR', 'Outerwear'), ('SHOES', 'Shoes'), ('BAG', 'Bag')], max_length=12)),
                ('color', models.CharField(max_length=40)),
                ('fit', models.CharField(choices=[('fitted', 'fitted'), ('relaxed', 'relaxed'), ('oversized', 'oversized'), ('tailored', 'tailored')], max_length=20)),
                ('formality', models.IntegerField(default=3)),
                ('warmth', models.IntegerField(default=2)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
